/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, Html } from "@react-three/drei";

export function Laptop({ currentScreen, ...props }) {
  const { nodes, materials } = useGLTF("/models/laptop.glb");

  console.log(currentScreen);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736_1.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736_2.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh485226736_3.geometry}
        material={materials.mat15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792.geometry}
        material={materials.mat16}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792_1.geometry}
        material={materials.mat23}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792_2.geometry}
        material={materials.mat17}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh256948792_3.geometry}
        material={materials.mat25}
      />
      {currentScreen === "Laptop" && (
        <Html
          position={[-0.025, 0.875, -0.6]}
          rotation={[0, 0, 0]}
          scale={0.1}
          transform
          occlude
        >
          <iframe
            src="https://www.teamaegis.fr/"
            style={{
              width: "1000px",
              height: "600px",
              border: "none",
            }}
          />
        </Html>
      )}
    </group>
  );
}

useGLTF.preload("/models/laptop.glb");
